### ISSUE TITLE
[Feature] Widget: Check if Glance widget is also working on API level < 28  in next Glance update

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#197]
See https://gitlab.com/techbeeat1/jtx/-/issues/519

**Comment by marvinlehmann** [comment]
Moin,

is this issue in any way related to?:

```
Launcher startActivityForResult is failed,the intent = Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=at.techbee.jtx/.ListWidgetConfigActivity (has extras) }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=at.techbee.jtx/.ListWidgetConfigActivity (has extras) } from ProcessRecord{97a5cf3 2716:com.huawei.android.launcher/u0a49} (pid=2716, uid=10049) not exported from uid 10246
	at android.os.Parcel.readException(Parcel.java:1946)
	at android.os.Parcel.readException(Parcel.java:1892)
	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4394)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1631)
	at android.app.Activity.startActivityForResult(Activity.java:4762)
	at android.app.Activity.startActivityForResult(Activity.java:4702)
	at com.huawei.android.launcher.Launcher.startActivityForResult(Launcher.java:4522)
	at com.huawei.android.launcher.Launcher.startActivityForResultSafely(Launcher.java:5878)
	at com.huawei.android.launcher.Launcher.addAppWidgetImpl(Launcher.java:4654)
	at com.huawei.android.launcher.Launcher.addAppWidgetFromDrop(Launcher.java:4757)
	at com.huawei.android.launcher.Workspace.addPendingAddItemInfoToDesktop(Workspace.java:10636)
	at com.huawei.android.launcher.WidgetCustomizeContainer$6.run(WidgetCustomizeContainer.java:907)
	at com.huawei.android.launcher.DragLayer$8.onAnimationEnd(DragLayer.java:1668)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:718)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

I'm on Android 8.0 and the Huawei Launcher apparently wants `android:exported="true"` @ https://github.com/TechbeeAT/jtxBoard/blob/22c2b315a75add701df8e287497bb69cebebb5c7/app/src/main/AndroidManifest.xml#L152-L162 to be able to create the widget. That's a different "exported" than the one below in the receiver element with the version notice.
I at least confirmed it to work on my device. I stumbled upon this through https://github.com/home-assistant/android/issues/2064 (much older than Glance).
I'm absolutely not up to date with Android programming though. All this API level and [target/compile/..]sdk stuff scared me off >.>

I hope you don't mind me hijacking this issue although it's probably not related (?)

**Comment by patrickunterwegs** [comment]
Hi @marvinlehmann , 
thanks for your comment. This problem doesn't seem to be related to the original bug here. 
Thanks for checking and also providing a possible solution!

I will set now both exported flags to true. 
Basically my understanding is that the flag defines if the activity or the receiver can be used by another app. It doesn't make sense, but I also don't see a security risk. So let's try it if it helps to fix a problem on your device. 
I will also set the receiver exported flag to true, because users have reported that in some cases the widget doesn't get updated.
