### ISSUE TITLE
[BUG] 403 Forbidden error when syncing recurring task to Fastmail in some cases

### ISSUE THREAD

**Issue by chewi** [TechbeeAT/jtxBoard#503]
## Describe the bug
If you use DAVx⁵ with a Fastmail account, you receive repeated 403 Forbidden errors when syncing a task that **ends never** or a task that was previously synced with some other recurrence but now has some other modification.

Perhaps this is a Fastmail issue. I can report it to them, but I think it may be handled better if it came from you, as you understand the details better than I do.

## To Reproduce
1. Create a new task to be stored on Fastmail.
2. Set a start date.
3. Enable recurrence with **ends never**.
4. Click the save icon.
5. Click the sync icon.

OR

1. Create a new task to be stored on Fastmail.
2. Set a start date.
3. Set a summary.
4. Enable recurrence with any setting other than **ends never**.
5. Click the save icon.
6. Click the sync icon.
7. Click the edit icon.
8. Change the summary.
9. Click the save icon.
10. Click the sync icon.
11. Close the app by swiping it away. This seems important.
12. Open the app again.
13. Select the task.
14. Click **Go to series**.
15. Click the edit icon.
16. Change the summary.
17. Click the save icon.
18. Click the sync icon.

Perhaps there's a shorter way to reproduce the latter, but I find you have to edit it more than once and you have to come out of the app at some point.

## Expected behavior
No 403 Forbidden errors should be seen.

## Device and version
 - Device: Motorola Edge (racer)
 - Android version: 13
 - jtx Board version: 2.04.00-beta01.gplay (204000000)
 - Downloaded from: Google Play

## Debug info (redacted)
```
--- BEGIN DEBUG INFO ---

SYNCHRONIZATION INFO
Account: Account {name=chewi@example.org, type=bitfire.at.davdroid}
Authority: at.techbee.jtx.provider

EXCEPTION
at.bitfire.dav4jvm.exception.ForbiddenException: HTTP 403 Forbidden
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:5)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:1)
	at at.bitfire.dav4jvm.DavResource.put(DavResource.kt:26)
	at at.bitfire.dav4jvm.DavResource.put$default(DavResource.kt:29)
	at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$3.invoke(SyncManager.kt:5)
	at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$3.invoke(SyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.uploadDirty(SyncManager.kt:16)
	at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1$1.invoke(SyncManager.kt:2)
	at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1$1.invoke(SyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.localExceptionContext(SyncManager.kt:8)
	at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1.invokeSuspend(SyncManager.kt:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

HTTP REQUEST
Request{method=PUT, url=https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/k@example.org.bec1e3f6-d998-4b40-b2e7-00ae4127811a/8fc3856c-6be9-4d36-89ce-cae667803ba4.ics, headers=[If-Match:"aac8693d3f813a852bfdc816800ff10811833339", User-Agent:DAVx5/4.3.1.1-gplay (2023/03/20; dav4jvm; okhttp/4.10.0) Android/13, Accept-Language:en-GB, en;q=0.7, *;q=0.5]}
BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN bitfire.at//ical4android (at.techbee.jtx)
BEGIN:VTODO
DTSTAMP:20230423T073502Z
UID:8fc3856c-6be9-4d36-89ce-cae667803ba4
SEQUENCE:98
CREATED:20230421T185542Z
LAST-MODIFIED:20230423T073457Z
SUMMARY:😁 Brush teeth
COLOR:lightgreen
CATEGORIES:Morning
DTSTART;VALUE=DATE:20230421
RRULE:FREQ=DAILY;COUNT=100;INTERVAL=-1
PRIORITY:0
END:VTODO
BEGIN:VTODO
DTSTAMP:20230423T073502Z
UID:8fc3856c-6be9-4d36-89ce-cae667803ba4
SEQUENCE:2
CREATED:20230422T090901Z
LAST-MODIFIED:20230422T090934Z
SUMMARY:😁 Brush teeth
COLOR:lightgreen
CATEGORIES:Morning
DTSTART;VALUE=DATE:20230422
RECURRENCE-ID;VALUE=DATE:20230422
PRIORITY:0
END:VTODO
END:VCALENDAR


HTTP RESPONSE
Response{protocol=http/1.1, code=403, message=Forbidden, url=https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/k@example.org.bec1e3f6-d998-4b40-b2e7-00ae4127811a/8fc3856c-6be9-4d36-89ce-cae667803ba4.ics}
<?xml version="1.0" encoding="utf-8"?>
<D:error xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <C:valid-calendar-data/>
  <D:responsedescription>Can't parse as RECUR value in RRULE property. Removing entire property: FREQ=DAILY;COUNT=100;INTERVAL=-1</D:responsedescription>
</D:error>


LOCAL RESOURCE
at.bitfire.davdroid.resource.LocalJtxICalObject@6f84f3f

REMOTE RESOURCE
https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/k@example.org.bec1e3f6-d998-4b40-b2e7-00ae4127811a/8fc3856c-6be9-4d36-89ce-cae667803ba4.ics

SOFTWARE INFORMATION

┌────────────────────────────────┬──────────────────────┬───────────┬─────────────────────┬───────┐
│ Package                        │ Version              │ Code      │ Installer           │ Notes │
├────────────────────────────────┼──────────────────────┼───────────┼─────────────────────┼───────┤
│ at.bitfire.davdroid            │ 4.3.1.1-gplay        │ 403010003 │ com.android.vending │       │
│ at.techbee.jtx                 │ 2.04.00-beta01.gplay │ 204000000 │ com.android.vending │       │
│ com.android.providers.contacts │ 13                   │ 33        │ —                   │       │
│ com.android.providers.calendar │ 13                   │ 33        │ —                   │       │
│ org.lineageos.etar             │ 13                   │ 33        │ —                   │       │
│ com.mixplorer                  │ 6.61.6               │ 23031310  │ com.mixplorer       │       │
│ com.kobobooks.android          │ 9.7.39690            │ 39690     │ com.android.vending │       │
└────────────────────────────────┴──────────────────────┴───────────┴─────────────────────┴───────┘


SYSTEM INFORMATION

Android version: 13 (lineage_racer-userdebug 13 TQ1A.230205.002 4a3683bd10)
Device: motorola Motorola Edge (racer)

Locale(s): [en_GB]
Time zone: Europe/London
Internal memory (/data): 93 GB free of 107 GB


CONNECTIVITY

 ☒ wlan0
   - [ Transports: WIFI Capabilities: NOT_METERED INTERNET NOT_RESTRICTED TRUSTED NOT_VPN VALIDATED NOT_ROAMING FOREGROUND NOT_CONGESTED NOT_SUSPENDED NOT_VCN_MANAGED LinkUpBandwidth>=48230Kbps LinkDnBandwidth>=50333Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, IP: /192.168.0.135, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 5, RSSI: -46, Link speed: 400Mbps, Tx Link speed: 400Mbps, Max Supported Tx Link speed: 400Mbps, Rx Link speed: 400Mbps, Max Supported Rx Link speed: 400Mbps, Frequency: 5560MHz, Net ID: -1, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none><none>MLO Information: , AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>> SignalStrength: -46 UnderlyingNetworks: Null]
   - DNS: 192.168.0.1, 192.168.0.254
 ☐ rmnet_data1
   - [ Transports: CELLULAR Capabilities: SUPL INTERNET NOT_RESTRICTED TRUSTED NOT_VPN VALIDATED NOT_ROAMING NOT_CONGESTED NOT_SUSPENDED NOT_VCN_MANAGED LinkUpBandwidth>=15000Kbps LinkDnBandwidth>=24489Kbps Specifier: <TelephonyNetworkSpecifier [mSubId = 1]> UnderlyingNetworks: Null]
   - DNS: 192.0.0.1, 2a00:23ee:0:8000::1, 2a00:23ee:0:8000::2

Data saver: disabled


CONFIGURATION

App standby bucket: 5
Power saving disabled: yes
System-wide synchronization: automatically

Notifications:
 - sync isBlocked=false
  * syncProblems: importance=3
  * syncIoErrors: importance=1
  * syncWarnings: importance=2
 - status: importance=2
 - general: importance=3
 - debug: importance=4

Permissions:
 - ACCESS_NETWORK_STATE: granted
 - ACCESS_WIFI_STATE: granted
 - FOREGROUND_SERVICE: granted
 - INTERNET: granted
 - POST_NOTIFICATIONS: granted
 - READ_SYNC_SETTINGS: granted
 - READ_SYNC_STATS: granted
 - WRITE_SYNC_SETTINGS: granted
 - RECEIVE_BOOT_COMPLETED: granted
 - REQUEST_IGNORE_BATTERY_OPTIMIZATIONS: granted
 - READ_CONTACTS: granted
 - WRITE_CONTACTS: granted
 - READ_CALENDAR: granted
 - WRITE_CALENDAR: granted
 - ACCESS_COARSE_LOCATION: denied
 - ACCESS_FINE_LOCATION: denied
 - ACCESS_BACKGROUND_LOCATION: denied
 - com.android.vending.BILLING: granted
 - org.dmfs.permission.READ_TASKS: denied
 - org.dmfs.permission.WRITE_TASKS: denied
 - org.tasks.permission.READ_TASKS: denied
 - org.tasks.permission.WRITE_TASKS: denied
 - at.techbee.jtx.permission.READ: granted
 - at.techbee.jtx.permission.WRITE: granted
 - WAKE_LOCK: granted
 - at.bitfire.davdroid.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted


ACCOUNTS

 - Account: chewi@example.org

┌──────────────────────────────────┬──────────┬───────────┬──────────┬───────────────────────────────────┐
│ Authority                        │ Syncable │ Auto-sync │ Interval │ Entries                           │
├──────────────────────────────────┼──────────┼───────────┼──────────┼───────────────────────────────────┤
│ at.bitfire.davdroid.addressbooks │ 0        │ false     │ —        │ —                                 │
│ com.android.calendar             │ 1        │ true      │ 240 min  │ 51 event(s)                       │
│ at.techbee.jtx.provider          │ 1        │ true      │ 15 min   │ 101 jtx Board ICalObject(s)       │
│ org.dmfs.tasks                   │ 0        │ false     │ 1440 min │ n/a                               │
│ org.tasks.opentasks              │ 0        │ false     │ 1440 min │ n/a                               │
│ com.android.contacts             │ 0        │ false     │ —        │ 0 wrongly assigned raw contact(s) │
└──────────────────────────────────┴──────────┴───────────┴──────────┴───────────────────────────────────┘

  WiFi only: false
  Contact group method: GROUP_VCARDS
  Time range (past days): 90
  Default alarm (min before): null
  Manage calendar colors: true
  Use event colors: false

 - Account: CardDAV

┌──────────────────────────────────┬──────────┬───────────┬──────────┬───────────────────────────────────┐
│ Authority                        │ Syncable │ Auto-sync │ Interval │ Entries                           │
├──────────────────────────────────┼──────────┼───────────┼──────────┼───────────────────────────────────┤
│ at.bitfire.davdroid.addressbooks │ 1        │ true      │ 240 min  │ —                                 │
│ com.android.calendar             │ 0        │ false     │ 1440 min │ 0 event(s)                        │
│ at.techbee.jtx.provider          │ 0        │ false     │ 1440 min │ 0 jtx Board ICalObject(s)         │
│ org.dmfs.tasks                   │ 0        │ false     │ 1440 min │ n/a                               │
│ org.tasks.opentasks              │ 0        │ false     │ 1440 min │ n/a                               │
│ com.android.contacts             │ 0        │ false     │ —        │ 0 wrongly assigned raw contact(s) │
└──────────────────────────────────┴──────────┴───────────┴──────────┴───────────────────────────────────┘

  WiFi only: false
  Contact group method: GROUP_VCARDS
  Time range (past days): 90
  Default alarm (min before): null
  Manage calendar colors: true
  Use event colors: false

  * Address book: Default (CardDAV eg)

    ┌──────────────────────┬──────────┬───────────┬──────────┬───────────────────┐
    │ Authority            │ Syncable │ Auto-sync │ Interval │ Entries           │
    ├──────────────────────┼──────────┼───────────┼──────────┼───────────────────┤
    │ com.android.contacts │ 1        │ true      │ —        │ 64 raw contact(s) │
    └──────────────────────┴──────────┴───────────┴──────────┴───────────────────┘

    URL: https://carddav.fastmail.com/dav/addressbooks/user/chewi@example.org/Default/
    Read-only: 0

  * Address book: Global Address Book (CardDAV zg)

    ┌──────────────────────┬──────────┬───────────┬──────────┬───────────────────┐
    │ Authority            │ Syncable │ Auto-sync │ Interval │ Entries           │
    ├──────────────────────┼──────────┼───────────┼──────────┼───────────────────┤
    │ com.android.contacts │ 1        │ true      │ —        │ 47 raw contact(s) │
    └──────────────────────┴──────────┴───────────┴──────────┴───────────────────┘

    URL: https://carddav.fastmail.com/dav/addressbooks/user/chewi@example.org/masteruser_automx6qjty@fastmail.com.Shared/
    Read-only: 0


DATABASE DUMP

android_metadata

┌────────┐
│ locale │
├────────┤
│ en_GB  │
└────────┘

service

┌────┬─────────────────────────┬─────────┬───────────────────────────────────────────────────────────────────────────┐
│ id │ accountName             │ type    │ principal                                                                 │
├────┼─────────────────────────┼─────────┼───────────────────────────────────────────────────────────────────────────┤
│ 3  │ chewi@example.org       │ caldav  │ https://caldav.fastmail.com/dav/principals/user/chewi@example.org/        │
│ 4  │ CardDAV                 │ carddav │ https://carddav.fastmail.com/dav/principals/user/chewi@example.org/       │
└────┴─────────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────┘

sqlite_sequence

┌─────────────────┬───────┐
│ name            │ seq   │
├─────────────────┼───────┤
│ service         │ 4     │
│ homeset         │ 4     │
│ syncstats       │ 22011 │
│ webdav_mount    │ 2     │
│ webdav_document │ 8     │
│ collection      │ 16    │
│ principal       │ 5     │
└─────────────────┴───────┘

homeset

┌────┬───────────┬──────────┬─────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────┐
│ id │ serviceId │ personal │ url                                                                         │ privBind │ displayName     │
├────┼───────────┼──────────┼─────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┤
│ 3  │ 3         │ 1        │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/           │ 1        │ James Le C      │
│ 4  │ 4         │ 1        │ https://carddav.fastmail.com/dav/addressbooks/user/chewi@example.org/       │ 1        │ #addressbooks   │
└────┴───────────┴──────────┴─────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────┘

syncstats

┌───────┬──────────────┬─────────────────────────┬───────────────┐
│ id    │ collectionId │ authority               │ lastSync      │
├───────┼──────────────┼─────────────────────────┼───────────────┤
│ 21997 │ 8            │ com.android.calendar    │ 1682231139471 │
│ 21998 │ 7            │ com.android.calendar    │ 1682231140253 │
│ 21999 │ 9            │ com.android.calendar    │ 1682231140481 │
│ 22000 │ 10           │ com.android.calendar    │ 1682231140708 │
│ 22001 │ 16           │ com.android.calendar    │ 1682231140936 │
│ 22003 │ 12           │ com.android.contacts    │ 1682231730288 │
│ 22004 │ 11           │ com.android.contacts    │ 1682231730294 │
│ 22011 │ 16           │ at.techbee.jtx.provider │ 1682235301280 │
└───────┴──────────────┴─────────────────────────┴───────────────┘

room_master_table

┌────┬──────────────────────────────────┐
│ id │ identity_hash                    │
├────┼──────────────────────────────────┤
│ 42 │ 67fafceecee2d97cac6a62d46fa2c3e2 │
└────┴──────────────────────────────────┘

webdav_mount

┌────┬──────┬─────┐
│ id │ name │ url │
├────┼──────┼─────┤
└────┴──────┴─────┘

webdav_document: 0 row(s), data not listed here

principal

┌────┬───────────┬──────────────────────────────────────────────────────────────────────────────────────┬─────────────────┐
│ id │ serviceId │ url                                                                                  │ displayName     │
├────┼───────────┼──────────────────────────────────────────────────────────────────────────────────────┼─────────────────┤
│ 1  │ 4         │ https://carddav.fastmail.com/dav/principals/user/chewi@example.org                   │ James Le C      │
│ 2  │ 3         │ https://caldav.fastmail.com/dav/principals/user/chewi@example.org                    │ James Le C      │
│ 3  │ 4         │ https://carddav.fastmail.com/dav/principals/user/masteruser_automx6qjty@fastmail.com │ —               │
│ 4  │ 3         │ https://caldav.fastmail.com/dav/principals/user/k@example.org                        │ K Le C          │
│ 5  │ 3         │ https://caldav.fastmail.com/dav/principals/user/m@example.org                        │ M Le C          │
└────┴───────────┴──────────────────────────────────────────────────────────────────────────────────────┴─────────────────┘

collection

┌────┬───────────┬───────────┬─────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┬────────────┬───────────────┬─────────────────────┬─────────────┬───────────┬──────────┬────────────────┬───────────────┬──────────────────┬────────┬──────┐
│ id │ serviceId │ homeSetId │ ownerId │ type         │ url                                                                                                                                  │ privWriteContent │ privUnbind │ forceReadOnly │ displayName         │ description │ color     │ timezone │ supportsVEVENT │ supportsVTODO │ supportsVJOURNAL │ source │ sync │
├────┼───────────┼───────────┼─────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┼────────────┼───────────────┼─────────────────────┼─────────────┼───────────┼──────────┼────────────────┼───────────────┼──────────────────┼────────┼──────┤
│ 7  │ 3         │ 3         │ 2       │ CALENDAR     │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/22be4888-543b-4747-88a2-950eeebf7361/                               │ 1                │ 1          │ 0             │ Family Calendar     │ —           │ -1528308  │ —        │ 1              │ 0             │ 0                │ —      │ 1    │
│ 8  │ 3         │ 3         │ 2       │ CALENDAR     │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/9d9e4304-5008-43c0-a9aa-83df2ef09825/                               │ 1                │ 1          │ 0             │ Chewi's Calendar    │ —           │ -15374912 │ —        │ 1              │ 0             │ 0                │ —      │ 1    │
│ 9  │ 3         │ 3         │ 4       │ CALENDAR     │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/k@example.org.3D074F2F-2C06-446E-B981-76332A6C4ECE/                 │ 1                │ 1          │ 0             │ K's Calendar        │ —           │ -6543440  │ —        │ 1              │ 0             │ 0                │ —      │ 1    │
│ 10 │ 3         │ 3         │ 5       │ CALENDAR     │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/m@example.org.D010E55B-ECF6-4631-AE17-DE4134E0FFE4/                 │ 1                │ 1          │ 0             │ M's Calendar        │ —           │ -1499549  │ —        │ 1              │ 0             │ 0                │ —      │ 1    │
│ 11 │ 4         │ 4         │ 1       │ ADDRESS_BOOK │ https://carddav.fastmail.com/dav/addressbooks/user/chewi@example.org/Default/                                                        │ 1                │ 1          │ 0             │ Default             │ —           │ —         │ —        │ —              │ —             │ —                │ —      │ 1    │
│ 12 │ 4         │ 4         │ 3       │ ADDRESS_BOOK │ https://carddav.fastmail.com/dav/addressbooks/user/chewi@example.org/masteruser_automx6qjty@fastmail.com.Shared/                     │ 1                │ 1          │ 0             │ Global Address Book │ —           │ —         │ —        │ —              │ —             │ —                │ —      │ 1    │
│ 16 │ 3         │ 3         │ 4       │ CALENDAR     │ https://caldav.fastmail.com/dav/calendars/user/chewi@example.org/k@example.org.bec1e3f6-d998-4b40-b2e7-00ae4127811a/                 │ 1                │ 1          │ 0             │ K's Tasks           │ —           │ -7617718  │ —        │ 1              │ 1             │ 0                │ —      │ 1    │
└────┴───────────┴───────────┴─────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴────────────┴───────────────┴─────────────────────┴─────────────┴───────────┴──────────┴────────────────┴───────────────┴──────────────────┴────────┴──────┘


APP SETTINGS

1. SharedPreferencesProvider canWrite=true

┌───────────────────────┬───────────┐
│ Setting               │ Value     │
├───────────────────────┼───────────┤
│ battery_optimization  │ true      │
│ distrust_system_certs │ false     │
│ foreground_service    │ false     │
│ proxy_host            │ localhost │
│ proxy_port            │ 8118      │
└───────────────────────┴───────────┘

2. DefaultsProvider canWrite=false

┌──────────────────────────────┬───────────┐
│ Setting                      │ Value     │
├──────────────────────────────┼───────────┤
│ default_sync_interval        │ 14400     │
│ distrust_system_certs        │ false     │
│ force_read_only_addressbooks │ false     │
│ proxy_host                   │ localhost │
│ proxy_port                   │ 9050      │
│ proxy_type                   │ -1        │
│ sync_all_collections         │ false     │
└──────────────────────────────┴───────────┘

--- END DEBUG INFO ---
```

**Comment by patrickunterwegs** [comment]
Hey @chewi !
Thanks for the issue report and detailed description!
I think I saw the basic error: 
`  <D:responsedescription>Can't parse as RECUR value in RRULE property. Removing entire property: FREQ=DAILY;COUNT=100;INTERVAL=-1</D:responsedescription>`

The interval should not be negative. I think it could be a problem in jtx Board, so maybe it's better not to contact Fastmail yet. I'll have a closer look soon and let you know!

**Comment by patrickunterwegs** [comment]
Hey @chewi !
I found the place, it is an issue in jtx Board, so thanks again :-)
I'll upload a new beta version to Google Play tomorrow at the latest!

**Comment by chewi** [comment]
Many thanks for your swift action here! I've tried the new beta, and while it does fix the first reproducer, I'm afraid it doesn't fix the second. The error message is the same with `INTERVAL=-1`.

**Comment by patrickunterwegs** [comment]
Hmm, you mean also new entries cause this error? Or is it still about the existing one? 
Actually I have only fixed the UI-problem, I didn't touch the existing entries. In your case, could you deactivate the recurrence, save and activate it again? This should actually solve it!

**Comment by chewi** [comment]
No, I mean that I gave two different ways to reproduce the error in my original post, and you have only fixed the first one. If I create a brand new task using the second method, I still get the error.

**Comment by patrickunterwegs** [comment]
Hi @chewi , I tried to reproduce the issue now in the latest beta step by step according to your description but I can't reproduce the problem. Would you mind creating a short video about how you create the error? Is there anything else suspicious during the process?

**Comment by chewi** [comment]
I've sent a video by email.

**Comment by duncan-blues** [comment]
Having a similar issue: When creating a new task with an alarm (e.g. when due), I keep getting a 403 forbidden error. The same task without the alarm is syncing fine.
When I add the alarm later e.g. using Gnome Evolution and sync it back to jtx, I'm getting the alarm just fine. Editing the alarm in jtx afterwards, e.g. changing it to "1 day before due", works as well.
Only adding a new alarm seems to cause this.

PS: Using web.de Caldav

**Comment by patrickunterwegs** [comment]
Thanks  @chewi  for the video, I tried to reproduce the error, regrettably without success... I will have another look tonight and tomorrow.

Thanks @duncan-blues , I don't think those issues are related. Could you also provide the DAVx5 error log for the case when that message appears for you?

**Comment by patrickunterwegs** [comment]
Hey @chewi , I still couldn't reproduce the error, but I have refactored the code a bit which could also help to avoid the issue. The new beta is available now on Google Play. Would you mind updating and trying again?

**Comment by chewi** [comment]
Thanks for trying. The new beta didn't help. I cleared all data from the app, but that didn't help either. I then deleted the "calendar" from DAVx⁵ and created a new one. This _did_ help, but this is my own calendar, whereas before it was my daughter's that had been shared with me. I'll double check by retrying the latter tomorrow.

**Comment by chewi** [comment]
Okay, so it only happens when working with someone else's calendar. I recreated my daughter's calendar and reproduced the issue again on my phone. I then went through the same procedure on her phone and it didn't happen. I then edited the task I'd just created on her phone with my phone and it happened again. Hopefully you're able to test that.

**Comment by patrickunterwegs** [comment]
Okay, thank you for the update, I'll check!

**Comment by patrickunterwegs** [comment]
Hi @chewi , I will get into this topic again, but just to be sure: did you make sure that your daughter's phone was also on the latest beta?

**Comment by chewi** [comment]
Yes, I did.

**Comment by patrickunterwegs** [comment]
Hi @chewi , I tried another fix, the problem is, that I still couldn't reproduce it, but what I do is trying to refactor places, where the interval is set. In this case I now specifically don't set the interval if it's 1 or less. May I ask you to try again? If you get an error, could you post the debug-info again? I'm actually wondering if it could still be the same error.

**Comment by chewi** [comment]
I think you got it this time! I can't reproduce it any more. :crossed_fingers: Thanks so much for your hard work on this.

**Comment by patrickunterwegs** [comment]
Thank you for the update, I'm glad it's gone and hopefully for good 😅
Thank you also for your checks and cooperation!
